### ISSUE TITLE
Whether this proj is finfished?

### ISSUE THREAD

**Issue by mycfhs** [Monalissaa/DisenDiff#1]
Hello, I'm trying to run this project and an error occurs.

│                                                                                         │
│ /home/dhw/yyc_workspace/paper_project/DisenDiff/src/model.py:429 in p_losses            │
│                                                                                         │
│   426 │   │   loss = self.l_simple_weight * loss.mean()                                 │
│   427 │   │                                                                             │
│   428 │   │   if self.controller is not None and (                                      │
│ ❱ 429 │   │   │   "<new1>" in origin_prompt[0] or "<new1>" in origin_prompt[1]          │
│   430 │   │   ):                                                                        │
│   431 │   │   │                                                                         │
│   432 │   │   │   batch_encoding = self.cond_stage_model.tokenizer(                     │
╰─────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: 'NoneType' object is not subscriptable

I found that the origin_prompt is None, and failed to resolve it. Any suggestions?

**Comment by Monalissaa** [comment]
Sorry about the forgotten modifications in the file while located at "stable-diffusion/ldm/models/diffusion/ddpm.py". Please change the `forward` function in the `DDPM` class to codes below,
```
def forward(self, x, c, *args, **kwargs):
        
        if self.random_change_subject_prompt:
            random_num = random.random()
            # 检查随机数是否大于 0.5
            if random_num > 0.5:
                for i in range(2):
                    # Use regular expression to find all matching strings in c[i]
                    # The matching strings are of the format '<new1> word and <new2> word'
                    matches = re.findall(r'<new1> \w+ and <new2> \w+', c[i])
                    # Iterate over each matching string
                    for match in matches:
                        # Split the matching string into two substrings
                        sub_string1, sub_string2 = match.split(' and ')
                        # Call the replace_substrings function to perform the replacement
                        self.replace_substrings(c, i, sub_string1, sub_string2)

        origin_prompt = c
        
        t = torch.randint(0, self.num_timesteps, (x.shape[0],), device=self.device).long()
        if self.model.conditioning_key is not None:
            assert c is not None
            ######################### here is the computation of token embedding
            if self.cond_stage_trainable:
                c = self.get_learned_conditioning(c, t=t)
            
            if self.shorten_cond_schedule:  # TODO: drop this option
                tc = self.cond_ids[t].to(self.device)
                c = self.q_sample(x_start=c, t=tc, noise=torch.randn_like(c.float()))

        return self.p_losses(x, c, t, origin_prompt, *args, **kwargs)
```
After that, adding the `replace_substrings` function as below,
```   
def replace_substrings(self, c, index, sub_string1, sub_string2):
        # Replace sub_string1 with a temporary string "TEMP"
        # Then replace sub_string2 with sub_string1
        # Finally replace "TEMP" with sub_string2
        # This effectively swaps sub_string1 and sub_string2
        c[index] = c[index].replace(sub_string1, "TEMP").replace(sub_string2, sub_string1).replace("TEMP", sub_string2)
``` 
I hope this could help you.

**Comment by mycfhs** [comment]
Thanks for your reply! Maybe you change the function&nbsp; 'get_learned_conditioning' in class LatentDiffusion too?
​





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Monalissaa/DisenDiff"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月9日(星期二) 上午10:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Monalissaa/DisenDiff] Whether this proj is finfished? (Issue #1)





 
Sorry about the forgotten modifications in the file while located at "stable-diffusion/ldm/models/diffusion/ddpm.py". Please change the forward function in the DDPM class to codes below,
 `    def forward(self, x, c, *args, **kwargs):
     if self.random_change_subject_prompt:         random_num = random.random()         # 检查随机数是否大于 0.5         if random_num &gt; 0.5:             for i in range(2):                 # Use regular expression to find all matching strings in c[i]                 # The matching strings are of the format '<new1&gt; word and <new2&gt; word'                 matches = re.findall(r'<new1&gt; \w+ and <new2&gt; \w+', c[i])                 # Iterate over each matching string                 for match in matches:                     # Split the matching string into two substrings                     sub_string1, sub_string2 = match.split(' and ')                     # Call the replace_substrings function to perform the replacement                     self.replace_substrings(c, i, sub_string1, sub_string2)     origin_prompt = c          t = torch.randint(0, self.num_timesteps, (x.shape[0],), device=self.device).long()     if self.model.conditioning_key is not None:         assert c is not None         ######################### here is the computation of token embedding         if self.cond_stage_trainable:             c = self.get_learned_conditioning(c, t=t)                  if self.shorten_cond_schedule:  # TODO: drop this option             tc = self.cond_ids[t].to(self.device)             c = self.q_sample(x_start=c, t=tc, noise=torch.randn_like(c.float()))     return self.p_losses(x, c, t, origin_prompt, *args, **kwargs)  
After that, adding thereplace_substringsfunction as below,
 def replace_substrings(self, c, index, sub_string1, sub_string2):
 # Replace sub_string1 with a temporary string "TEMP"
 # Then replace sub_string2 with sub_string1
 # Finally replace "TEMP" with sub_string2
 # This effectively swaps sub_string1 and sub_string2
 c[index] = c[index].replace(sub_string1, "TEMP").replace(sub_string2, sub_string1).replace("TEMP", sub_string2)
 `
 I hope this could help you.

**Comment by mycfhs** [comment]
Thanks for your reply! Maybe you change the function&nbsp; 'get_learned_conditioning' in class LatentDiffusion too? For there's missing a param 't'
​&nbsp;

paper_project/DisenDiff/ldm/models/diffusion/ddpm.py:1139 in&nbsp; │
│ forward&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;│
│&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;│
│&nbsp; &nbsp;1136 │&nbsp; &nbsp;│&nbsp; &nbsp;│&nbsp; &nbsp;assert c is not None&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;│
│&nbsp; &nbsp;1137 │&nbsp; &nbsp;│&nbsp; &nbsp;│&nbsp; &nbsp;######################### here is the computation of token embeddi │
│&nbsp; &nbsp;1138 │&nbsp; &nbsp;│&nbsp; &nbsp;│&nbsp; &nbsp;if self.cond_stage_trainable:&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; │
│ ❱ 1139 │&nbsp; &nbsp;│&nbsp; &nbsp;│&nbsp; &nbsp;│&nbsp; &nbsp;c = self.get_learned_conditioning(c, t=t)&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; │
│&nbsp; &nbsp;1140 │&nbsp; &nbsp;│&nbsp; &nbsp;│&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; │
│&nbsp; &nbsp;1141 │&nbsp; &nbsp;│&nbsp; &nbsp;│&nbsp; &nbsp;if self.shorten_cond_schedule:&nbsp; # TODO: drop this option&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;│
│&nbsp; &nbsp;1142 │&nbsp; &nbsp;│&nbsp; &nbsp;│&nbsp; &nbsp;│&nbsp; &nbsp;tc = self.cond_ids[t].to(self.device)&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; │
╰───────────────────────────────────────────────────────────────────────────────────────╯
TypeError: get_learned_conditioning() got an unexpected keyword argument 't'






------------------ 原始邮件 ------------------
发件人:                                                                                                                        "Monalissaa/DisenDiff"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月9日(星期二) 上午10:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Monalissaa/DisenDiff] Whether this proj is finfished? (Issue #1)





 
Sorry about the forgotten modifications in the file while located at "stable-diffusion/ldm/models/diffusion/ddpm.py". Please change the forward function in the DDPM class to codes below,
 `    def forward(self, x, c, *args, **kwargs):
     if self.random_change_subject_prompt:         random_num = random.random()         # 检查随机数是否大于 0.5         if random_num &gt; 0.5:             for i in range(2):                 # Use regular expression to find all matching strings in c[i]                 # The matching strings are of the format '<new1&gt; word and <new2&gt; word'                 matches = re.findall(r'<new1&gt; \w+ and <new2&gt; \w+', c[i])                 # Iterate over each matching string                 for match in matches:                     # Split the matching string into two substrings                     sub_string1, sub_string2 = match.split(' and ')                     # Call the replace_substrings function to perform the replacement                     self.replace_substrings(c, i, sub_string1, sub_string2)     origin_prompt = c          t = torch.randint(0, self.num_timesteps, (x.shape[0],), device=self.device).long()     if self.model.conditioning_key is not None:         assert c is not None         ######################### here is the computation of token embedding         if self.cond_stage_trainable:             c = self.get_learned_conditioning(c, t=t)                  if self.shorten_cond_schedule:  # TODO: drop this option             tc = self.cond_ids[t].to(self.device)             c = self.q_sample(x_start=c, t=tc, noise=torch.randn_like(c.float()))     return self.p_losses(x, c, t, origin_prompt, *args, **kwargs)  
After that, adding thereplace_substringsfunction as below,
 def replace_substrings(self, c, index, sub_string1, sub_string2):
 # Replace sub_string1 with a temporary string "TEMP"
 # Then replace sub_string2 with sub_string1
 # Finally replace "TEMP" with sub_string2
 # This effectively swaps sub_string1 and sub_string2
 c[index] = c[index].replace(sub_string1, "TEMP").replace(sub_string2, sub_string1).replace("TEMP", sub_string2)
 `
 I hope this could help you.

**Comment by Monalissaa** [comment]
Yes, you are right. Please forgive my carelessness and change the `get_learned_conditioning` function to codes below:
```
    def get_learned_conditioning(self, c, t=None):
        if self.cond_stage_forward is None:
            if hasattr(self.cond_stage_model, 'encode') and callable(self.cond_stage_model.encode):
                c = self.cond_stage_model.encode(c, t)
                if isinstance(c, DiagonalGaussianDistribution):
                    c = c.mode()
            else:
                c = self.cond_stage_model(c)
        else:
            assert hasattr(self.cond_stage_model, self.cond_stage_forward)
            c = getattr(self.cond_stage_model, self.cond_stage_forward)(c)
        return c
```

**Comment by mycfhs** [comment]
Thanks for patiently answering my questions!&nbsp;Your idea is very excellent. Good luck getting accepted!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Monalissaa/DisenDiff"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月9日(星期二) 中午11:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Monalissaa/DisenDiff] Whether this proj is finfished? (Issue #1)





 
Yes, you are right. Please forgive my carelessness and change the get_learned_conditioning function to codes below:
     def get_learned_conditioning(self, c, t=None):         if self.cond_stage_forward is None:             if hasattr(self.cond_stage_model, 'encode') and callable(self.cond_stage_model.encode):                 c = self.cond_stage_model.encode(c, t)                 if isinstance(c, DiagonalGaussianDistribution):                     c = c.mode()             else:                 c = self.cond_stage_model(c)         else:             assert hasattr(self.cond_stage_model, self.cond_stage_forward)             c = getattr(self.cond_stage_model, self.cond_stage_forward)(c)         return c
