### ISSUE TITLE
请问代码中将new token以外的词的token_embedding冻结住的部分在哪里，还是说所有的token_embedding都重新训练了呢

### ISSUE THREAD

**Issue by Dumeowmeow** [Monalissaa/DisenDiff#6]

**Comment by Monalissaa** [comment]
没有冻结，是在计算的时候把其他token_embedding的梯度detach了，所以也只是训练了new token，详见 [here](https://github.com/Monalissaa/DisenDiff/blob/89b8927592d1dee30cba629296b3715ffb7dcf4b/src/custom_modules.py#L305) ，这种方式是与custom diffusion一致的。

**Comment by Dumeowmeow** [comment]
> 没有冻结，是在计算的时候把其他token_embedding的梯度detach了，所以也只是训练了new token，详见 [here](https://github.com/Monalissaa/DisenDiff/blob/89b8927592d1dee30cba629296b3715ffb7dcf4b/src/custom_modules.py#L305) ，这种方式是与custom diffusion一致的。

谢谢您，我的互联网恩师。
